[package]
name = "organism-sorting"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
indicatif = "0.16"
rayon = "1.10.0"
